Repository ez-algorithm/algorithm, pull requests merged in 2022-04, with the labels that each got.

#31 하현숙 : let 16 3Sum Closet
  hyeonsook95/leetcode/16.py
  hyeonsook95/leetcode/16.ts
Labels: leetcode, 투포인터

#35 심규환 : 모든 문제
  sgh1939/baekjoon/9095.cpp
  sgh1939/baekjoon/9095.exe
  sgh1939/baekjoon/9461.cpp
  sgh1939/baekjoon/9461.exe
  sgh1939/leetcode/76. Minimum Window Substring.cpp
  sgh1939/leetcode/76. Minimum Window Substring.exe
  sgh1939/leetcode/76.cpp
  sgh1939/leetcode/76.exe
Labels: leetcode, 재귀

#32 하현숙 : boj 1913 달팽이
  hyeonsook95/baekjoon/1913.py
  hyeonsook95/baekjoon/1913.ts
Labels: boj, 구현

#34 이정환 : leet 16 3Sum closest
  edd0718/backjoon/1913.cpp
  edd0718/leetcode/leet-16.cpp
Labels: leetcode, 투포인터

#33 이정환 : boj 1913 달팽이
  edd0718/backjoon/1913.cpp
Labels: boj, 구현

#36 하현숙 : boj 10798 세로읽기
  hyeonsook95/baekjoon/10798.py
  hyeonsook95/baekjoon/10798.ts
Labels: boj, 구현

#37 하현숙 : boj 13229 Selection Sum
  hyeonsook95/baekjoon/13229/13229.py
  hyeonsook95/baekjoon/13229/13229.ts
  hyeonsook95/baekjoon/13229/13229_1.py
Labels: boj, 누적합

#38 하현숙 : boj 10025 게으른 백곰
  hyeonsook95/baekjoon/10025.py
  hyeonsook95/baekjoon/10025.ts
Labels: boj, 투포인터, 슬라이딩윈도우

#47 규환 백준 2302 dp 극장좌석
  sgh1939/baekjoon/2302.cpp
Labels: 다이나믹프로그래밍

#45 하현숙 : boj 11726 2*n 타일링
  hyeonsook95/baekjoon/11726.py
  hyeonsook95/baekjoon/11726.ts
Labels: boj, 다이나믹프로그래밍

#51 김현아 : 백준 11726 2xn 타일링
  kha/boj/11726.py
Labels: boj, 다이나믹프로그래밍

#54 이정환 : boj 11726 dp 2xn 타일링
  edd0718/backjoon/11726.cpp
  edd0718/backjoon/2302.cpp
Labels: boj, 다이나믹프로그래밍

#53 이정환 : boj 2302 구현 극장좌석
  edd0718/backjoon/2302.cpp
Labels: boj, 구현

#49 김현아 : 백준 2302 극장좌석
  kha/boj/2302.py
Labels: boj, 다이나믹프로그래밍

#48 규환 백준 11726 dp 2xn 타일링
  sgh1939/baekjoon/11726.cpp
Labels: 다이나믹프로그래밍

#46 하현숙 : boj 2302 dp 극장좌석
  hyeonsook95/baekjoon/2302.py
Labels: boj, 다이나믹프로그래밍

#55 하현숙 : BOJ 15591 MooTube
  hyeonsook95/baekjoon/15591.py
Labels: boj, bfs

#52 강일훈 : boj 11726 dp 2*n타일링
  ilhoon93/boj/boj-11726.py
  ilhoon93/boj/boj-2302.py
Labels: boj, 다이나믹프로그래밍

#50 강일훈 : boj 2302 dp 극장좌석
  ilhoon93/boj/boj-2302.py
Labels: boj, 다이나믹프로그래밍

#69 김현아 : 프로그래머스 68645 삼각 달팽이
  kha/programmers/68645.py
Labels: programmers, 구현

#65 김현아 : 백준 2437 저울
  kha/boj/2437.py
Labels: boj, greedy

#59 김현아 : 백준 2493 탑
  kha/boj/2493.py
Labels: boj, 구현

#58 김현아 : 백준 1246 온라인 판매
  kha/boj/1246.py
Labels: boj, greedy

#61 심규환 boj 1246 온라인 판매
  sgh1939/baekjoon/1246.cpp
Labels: boj

#62 심규환 boj 2493 탑
  sgh1939/baekjoon/2493.cpp
Labels: 스택

#63 심규환 boj 2437 저울
  sgh1939/baekjoon/2437.cpp
Labels: boj, greedy

#64 심규환 programers 68645 삼각당팽이
  sgh1939/programmers/삼각달팽이.cpp
Labels: programmers, 구현

#56 하현숙 programers 68645 삼각 달팽이
  hyeonsook95/programers/68645.py
Labels: programmers, 구현

#57 하현숙 boj 1246 온라인판매
  hyeonsook95/baekjoon/1246.py
Labels: boj, 구현

#60 하현숙 boj 2493 탑
  hyeonsook95/baekjoon/2493.py
Labels: boj, 스택

#73 강일훈 : boj 1246 온라인판매
  ilhoon93/boj/boj-1246.py
Labels: boj, greedy

#74 강일훈 : boj 2437 저울
  ilhoon93/boj/boj-2437.py
Labels: boj, greedy

#75 강일훈 : boj 2493 탑
  ilhoon93/boj/boj-2493.py
Labels: boj, 스택

#77 code : 김현아 백준 16506 구현 CPU
  kha/boj/16506.py
Labels: boj, 구현

#80 김현아 : 백준 11559 Puyo Puyo
  kha/boj/11559.py
Labels: boj, 구현

#76 김현아 : 프로그래머스 12981 영어 끝말잇기
  kha/programmers/12981.py
Labels: programmers, 구현

#88 김현아 : leetcode 55 Jump Game
  kha/leetcode/55.py
Labels: leetcode, greedy

#89 하현숙 : let 55 Jump Game
  hyeonsook95/leetcode/55.py
Labels: leetcode, 백트래킹

#90 하현숙 : pro 12981 구현 영어끝말잇기
  hyeonsook95/programers/12981.py
Labels: programmers, 구현

#91 하현숙 : boj 16506 CPU
  hyeonsook95/baekjoon/16506.py
Labels: boj, 구현

#84 심규환 baekjoon 16506 CPU
  sgh1939/baekjoon/16506.cpp
Labels: boj, 구현

#83 심규환 programmers 영어 끝말잇기
  sgh1939/programmers/영어 끝말잇기.cpp
Labels: programmers

#87 심규환 baekjoon 11559 puyo puyo
  sgh1939/baekjoon/11559.cpp
  sgh1939/leetcode/53. Jump Game.cpp
Labels: boj, dfs
